### ISSUE TITLE
Light and dark themes

### ISSUE THREAD

**Issue by BrandonEscamilla** [datalayer/jupyter-ui#104] opened 2023-09-26 12:24 UTC
Hi @echarles, In previous discussions, we touched upon the topic of themes. I would like to inquire about the current status of theme development and if there are any workarounds to enable themes before they are officially incorporated into the library. I attempted the approaches discussed in this thread (https://github.com/datalayer/jupyter-ui/issues/85), but so far not working. Do you have any insights or suggestions that could help? Thank you in advance!

**Comment by echarles** [comment] 2023-09-26 18:09
I have added a `theme` prop on the Jupyter context and it works.

<img width="815" alt="Screenshot 2023-09-26 at 20 07 54" src="https://github.com/datalayer/jupyter-ui/assets/226720/84c66477-0fa9-4878-9ab2-8a2b2e2fd876">

**Comment by echarles** [comment] 2023-09-26 18:12
And this is theme support with the new JupyterLabApp component being worked out.

![Untitled6](https://github.com/datalayer/jupyter-ui/assets/226720/046bb75f-6030-4a93-943b-a0568638db5f)

**Comment by echarles** [comment] 2023-09-27 08:30
@BrandonEscamilla Just released `0.7.8` which adds a `theme` prop in the `Jupyter` context component.

There is an `NotebookThemed` example in https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/NotebookThemed.tsx

For now, going from light to dark works fine, but going from dark to light does not reload the CSS (because the theme css needs to be force reloaded, still need to find a way to implement that). I guess for now, it is already a good step to initialize the context with a specified theme.

**Comment by echarles** [comment] 2023-09-27 08:32
The `NotebookThemed` example has a switch to go from light to dark.

![Untitled6](https://github.com/datalayer/jupyter-ui/assets/226720/08427515-bdd5-4ea2-930e-bc4fb65ee90e)

**Comment by BrandonEscamilla** [comment] 2023-09-27 11:53
Hey @echarles, in fact the new release works as expected! thanks! looking forward when the dark->light works.

**Comment by echarles** [comment] 2023-09-27 12:28
This is now working in main branch only for the `JupyterLabApp` component. I would like to invest more time to have a parity with this new approach with the current `Notebook` component instead of investing more to fix the theming dark->light.

![Untitled6](https://github.com/datalayer/jupyter-ui/assets/226720/60d69162-086f-4c4e-93dd-46b371229ec5)

**Comment by BrandonEscamilla** [comment] 2023-10-16 07:25
Hi @echarles! I've been out of the loop for a few weeks. Could you please clarify if the headless JupyterLab app is planned to become the default way of using Jupyter React in the future? If so, do you know when this transition might occur? I've noticed that most of the required features appear to be fully supported in that version, is that correct? Thank you!

**Comment by echarles** [comment] 2023-10-16 07:36
> Hi @echarles! I've been out of the loop for a few weeks.

Great to see you back

> Could you please clarify if the headless JupyterLab app is planned to become the default way of using Jupyter React in the future?

I confirm it will be the default.

> If so, do you know when this transition might occur?

I am squeezing between a lot of things... maybe in 1 month? I should have more manpower at Datalayer in December, so many things will for sure be unblocked in December.

> I've noticed that most of the required features appear to be fully supported in that version, is that correct? Thank you!

Yes, it is a much more powerful approach, leveraging any extension/plugin system. We just need to make sure the existing props of the Notebook component behave as before, especially in terms of nbformat, kernel change.

**Comment by echarles** [comment] 2023-12-13 07:59
> > Could you please clarify if the headless JupyterLab app is planned to become the default way of using Jupyter React in the future?

> I confirm it will be the default.

@BrandonEscamilla After a few more iterations and with more background, the JupyterLabApp (headless or not) is great for developers that are willing to leverage a complete set of JupyterLab plugins. However, for developers just willing the basics (a cell, a notebook), it sounds maybe that the current Cell, Notebook... components are a good fit : they can be tuned to do a specific job and they load much faster (the jupyterlab extension system is notably "slow" to inject the full dependency tree) - We may thus further push to better support light/dark themes in the current components, or find a way to have a faster injection system (cc/ @fcollonval)

**Comment by echarles** [comment] 2024-01-16 18:03
@BrandonEscamilla I have just merged a PR https://github.com/datalayer/jupyter-ui/pull/181 implemented by @fcollonval.

This should bring features that answers your requests. Are they all covered? I can cut a release when you are willing to test.

**Comment by BrandonEscamilla** [comment] 2024-01-18 14:23
Hi @echarles, thank you for following up with this request. I think next week I will be have some time to test the new version, so let me know if when you release to proceed with testing. Thanks!

**Comment by echarles** [comment] 2024-01-20 14:52
Hi @BrandonEscamilla jupyter-react 0.9.0 is released. Please try and report any issue, question, feedback or feature request :)
Thank you again 🙏

**Comment by echarles** [comment] 2024-01-20 15:27
Better use 0.9.1 (deps fix)

**Comment by BrandonEscamilla** [comment] 2024-01-22 15:06
Hi @echarles, it seems there are some issues with 0.9.1. I list them below:

- Every time I opened the notebook I see the following error: Error "Starting Kernel, Failed to fetch"
- In order to make it work I needed to update my next.config.js due to pyodide being included now 
- Finally, new colorMode implementation doesn't work for me, it changes from dark to light but not in the other way around

**Comment by echarles** [comment] 2024-01-22 16:15
> Every time I opened the notebook I see the following error: Error "Starting Kernel, Failed to fetch"

Does it happen with the examples of this repo or with your own repo?

> In order to make it work I needed to update my next.config.js due to pyodide being included now

yeah, that is a not so nice side effect of the introduction of the lite for all the components, the wepack needs to be updated. I believe that is a price to pay for a very good feature.

> Finally, new colorMode implementation doesn't work for me, it changes from dark to light but not in the other way around

Here is a recording of my local env. It looks like I have to (force) refresh the page (saw that before). Could try that?

[Screencast from 22-01-24 17:04:16.webm](https://github.com/datalayer/jupyter-ui/assets/226720/75535a37-163f-4964-ba33-4a4e8c19d2f6)

**Comment by BrandonEscamilla** [comment] 2024-01-23 12:28
Yes, failed to fetch happens with my own repo. With respect to dark mode, the behavior is the same after reloading.

**Comment by echarles** [comment] 2024-01-23 12:40
> Yes, failed to fetch happens with my own repo. With respect to dark mode, the behavior is the same after reloading.

Do you have a public reproducer?

**Comment by fcollonval** [comment] 2024-01-23 12:57
In #181, to fix the colorMode switch I had to change the [webpack rules](https://github.com/datalayer/jupyter-ui/pull/181/files#diff-db5ea275659f439bfc7ba8d25b063986ca0e8cbafa54effb8bb5853520a51ce9)

```diff
-      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
+      // We must escape the JupyterLab theme style sheets to apply specific rules
+      // this is only needed in stand-alone mode
+      { test: /(?<!style\/theme)\.css$/, use: ['style-loader', 'css-loader'] },
+      // Special webpack rule for the JupyterLab theme style sheets.
+      {
+        test: /style\/theme\.css$/i,
+        loader: 'css-loader',
+        options: { exportType: 'string' },
+      },
```

And bump `css-loader` to `^6.3.0`

**Comment by echarles** [comment] 2024-01-23 13:27
Looks like webpack is config is growing at a point where we should package it to make developers life easier. I have opened https://github.com/datalayer/jupyter-ui/issues/187 to track this.

**Comment by BrandonEscamilla** [comment] 2024-01-23 13:55
> > Yes, failed to fetch happens with my own repo. With respect to dark mode, the behavior is the same after reloading.
> 
> Do you have a public reproducer?

I don't think so. But my case is very similar to the one [here](https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/NotebookColorMode.tsx), the only difference is that my variable colorMode is obtained through useTheme() from next-theme package.

> In #181, to fix the colorMode switch I had to change the [webpack rules](https://github.com/datalayer/jupyter-ui/pull/181/files#diff-db5ea275659f439bfc7ba8d25b063986ca0e8cbafa54effb8bb5853520a51ce9)
> 
> ```diff
> -      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
> +      // We must escape the JupyterLab theme style sheets to apply specific rules
> +      // this is only needed in stand-alone mode
> +      { test: /(?<!style\/theme)\.css$/, use: ['style-loader', 'css-loader'] },
> +      // Special webpack rule for the JupyterLab theme style sheets.
> +      {
> +        test: /style\/theme\.css$/i,
> +        loader: 'css-loader',
> +        options: { exportType: 'string' },
> +      },
> ```
> 
> And bump `css-loader` to `^6.3.0`

So do I need to include these ones as well?

**Comment by echarles** [comment] 2024-01-23 14:01
> I don't think so. But my case is very similar to the one [here](https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/NotebookColorMode.tsx), the only difference is that my variable colorMode is obtained through useTheme() from next-theme package.

Thx for sharing that information. the useTheme() is indeed similar to the example we have with primer.

> So do I need to include these ones as well?

Yes, you have to.

**Comment by BrandonEscamilla** [comment] 2024-01-23 15:57
Hi @echarles, I included the webpack rules and installed styled-loader and css-loader, and see this error now: 
```
 ⨯ ./node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/node_modules/@jupyterlab/codemirror/style/base.css:5:0
Module not found: Invalid generator object. Asset Modules Plugin has been initialized using a generator object that does not match the API schema.
 - generator has an unknown property 'filename'. These properties are valid:
   object { dataUrl? }
   -> Generator options for asset/inline modules.

https://nextjs.org/docs/messages/module-not-found
```

**Comment by echarles** [comment] 2024-01-23 16:14
mmh sounds like a deps/resolution issue that does not pull the correct version. To be sure, I 'd like to add the color scheme switcth to our next.js example.

Could yo paste a snippet of what you are doing for the color scheme switch in next.js (with the imports), tbh I am not very familiar with the next.js api. From there I will try to work out something.

**Comment by BrandonEscamilla** [comment] 2024-01-23 16:37
Sure, it's very simple but here you go. I skip stuff that I think is not related to this.

```
"use client";
import { useCallback, useState, useRef, useEffect } from 'react';
import { useTheme } from "next-themes";
import { injectableStore } from "@/redux/store";
import { INotebookContent,  } from '@jupyterlab/nbformat';
import { Button } from "@/components/ui/button"
import { Jupyter,  selectNotebookModel, Notebook, CellSidebar, Viewer } from '@datalayer/jupyter-react';
import NotebookToolbar from '@/components/notebook-toolbar';

export default function UserNotebook() {
    const { theme } = useTheme();
    const NOTEBOOK_UID = "notebook-id"
    const [nbformat, setNbFormat] = useState<INotebookContent>();
    const [nbformatDialog, setNbFormatDialog] = useState<INotebookContent>();
    const [updatedNbFormat, setUpdatedNbFormat] = useState<INotebookContent>();

    return (
      <Jupyter
          colorMode={theme === "light" ? "light" : "dark"}   
          injectableStore={injectableStore}
          jupyterServerHttpUrl="https://..."
          jupyterServerWsUrl="wss://..."
          jupyterToken="..."                    
      >                
        <div className="w-full mx-auto px-2 sm:px-6 lg:px-8 py-4">    
                  <Notebook                
                      nbformat={nbformat}
                      path={path}
                      CellSidebar={CellSidebar}                                                             
                      Toolbar={NotebookToolbar}
                      bundledIPyWidgets={[ 
                        { name: "jupyter-matplotlib", version: "0.11.3", module: require("jupyter-matplotlib")} 
                      ]} 
                      height='calc(100vh - 2.6rem)'
                      cellSidebarMargin={120}                
                      uid={NOTEBOOK_UID}                
                  />
        </div>
      </Jupyter>
    )
}

```

**Comment by echarles** [comment] 2024-01-25 13:32
> Generator options for asset/inline modules.

@BrandonEscamilla I have updated the example in https://github.com/datalayer/jupyter-ui/commit/cfbcb2a1e9e7cc81a39937a07d54f2e01f0573c4 and can reproduce the error you have reported. At least the main branch has now an example where you can toggle from light to dark. Then after dark to light does not change the noteobook.

I have seen a few case in the next.js repos with that same error.

**Comment by BrandonEscamilla** [comment] 2024-01-31 10:43
Hi @echarles, so is it working? or still in progress? Thank you in advance!

**Comment by echarles** [comment] 2024-01-31 12:29
> Hi @echarles, so is it working? or still in progress?

It is working for non-next.js app

It is not working for next.js app. No idea atm how to fix for next.js cases. I guess this is possible, but would need more time to digg into.

**Comment by echarles** [comment] 2024-05-07 14:12
Just opened https://github.com/datalayer/jupyter-ui/pull/213 to fix this.

**Closed** 2024-05-07 14:22 UTC
Labels: feature
