### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by rrickyp** [datalayer/jupyter-ui#86] opened 2023-08-09 06:20 UTC
I am using Next.js. However, I always get this error
```
./node_modules/@datalayer/jupyter-react/lib/components/cell/Cell.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@datalayer/jupyter-react/lib/components/cell/Cell.js
```
May I know how to solve this? Thanks in advance

**Comment by echarles** [comment] 2023-08-09 08:44
Hi @rrickyp I don't receive that error with the example in this repo. Do you have a public repo to reproduce it?

**Comment by rrickyp** [comment] 2023-08-10 07:24
Thanks for the reply, I have fixed it already, it turns out there is something wrong with my project, and I solved it by putting
```
const withTM = require('next-transpile-modules')([
    '@fortawesome/fontawesome-free',
    '@jupyter-widgets/base',
    '@jupyter-widgets/jupyterlab-manager',
    '@jupyter-widgets/controls',
    '@jupyter-widgets/html-manager',
  ])
const nextConfig = {  experimental: {
    esmExternals: `loose`
  }}
module.exports = withTM(nextConfig)

``` 
inside my next.config.js

**Comment by echarles** [comment] 2023-08-10 08:24
I have cloned your https://github.com/rrickyp/jupyter_test and added `"@datalayer/jupyter-react": "0.5.2"` to the dependencies.

I had also to add the following to avoid errors messages in the console

```json
  "devDependencies": {
    "bufferutil": "4.0.7",
    "encoding": "0.1.13",
    "utf-8-validate": "6.0.3"
  },
```

Also, ensure you are using Yarn 3.5, and add [.yarnrc.yml](https://github.com/datalayer/jupyter-ui/blob/main/.yarnrc.yml) in the root of your repo.

Then I received CORS errors in the console, which I suspect was not really the real source. So I had to set resolutions, just copied/pasted the following, and the it worked out, I see Cell and Notebook in Next.js app https://github.com/datalayer/jupyter-ui/blob/5ac809e17ac9949b0371c58deacdb4d00d30ffe7/package.json#L75-L181

(looks like we need to bump and use jupyterlab 4.0.4, for now we sit on 4.0.3)

**Comment by rrickyp** [comment] 2023-08-10 09:14
Thanks. it works now

**Comment by echarles** [comment] 2023-08-10 09:31
Great! Closing as resolved. Please open a new issue if needed.

**Closed by echarles** 2023-08-10 09:31 UTC
Labels: bug

**Comment by VisheshNucleusTeq** [comment] 2024-04-15 21:41
<img width="552" alt="Screenshot 2024-04-16 at 3 11 28 AM" src="https://github.com/datalayer/jupyter-ui/assets/67576528/634390c4-520e-4718-925f-0b0aa21e8e5b">
